### ISSUE TITLE
What is going on here?

### ISSUE THREAD

**Issue by 0xIO32** [litegapps/updater#1]
In the last 12 hours there are version updates commited to this repo.

On this page: https://litegapps.github.io/download/litegapps/arm64/33/, the sourceforge download is replaced with:
"https://www.toprevenuegate.com/b9p0mwvwgs?key=c882ea866d79e457f018e720ee79a171"

Also the update.json for Magisk etc. is updated with a strange version and this link.

An explanation would be nice.

**Comment by wahyu6070** [comment]
saya sedang melakukan uji coba ,, sekarang sudah saya kembalikan ke semula
